# Generated by Django 4.0.3 on 2022-05-17 20:20

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blogImage',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.filepath),
        ),
    ]
