# Generated by Django 4.0.3 on 2022-05-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogmodel_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(default='Action', max_length=50),
            preserve_default=False,
        ),
    ]
