# Generated by Django 4.0.3 on 2022-05-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phNo', models.CharField(max_length=13)),
                ('date', models.DateField()),
            ],
        ),
    ]
